<?php
// AntiSpam Shield — PHP Admin Panel Configuration

$dbDir = getenv('ANTISPAM_DATA_DIR') ?: realpath(__DIR__ . '/../../data');
define('DB_PATH', $dbDir . '/antispam.db');
define('APP_NAME', 'AntiSpam Shield');
define('SESSION_LIFETIME', 86400); // 24 hours

// Base path for reverse proxy (e.g. '/php' when served under /php/)
$basePath = getenv('APP_BASE_PATH') ?: '';
define('BASE_PATH', rtrim($basePath, '/'));

function basePath(string $path = ''): string {
    return BASE_PATH . $path;
}

// Translations
$LANG = [
    'ru' => [
        'app_title' => 'AntiSpam Shield',
        'app_subtitle' => 'Панель управления',
        'nav_projects' => 'Проекты',
        'nav_logout' => 'Выйти',
        'login_title' => 'Вход в систему',
        'login_username' => 'Логин',
        'login_password' => 'Пароль',
        'login_submit' => 'Войти',
        'login_error' => 'Неверный логин или пароль',
        'projects_title' => 'Проекты',
        'projects_add' => 'Добавить проект',
        'projects_name' => 'Название',
        'projects_domain' => 'Домен',
        'projects_stats' => 'Статистика',
        'projects_details' => 'Подробно',
        'projects_delete' => 'Удалить',
        'projects_delete_confirm' => 'Вы уверены, что хотите удалить проект',
        'projects_empty' => 'Нет проектов. Создайте первый!',
        'new_project_title' => 'Новый проект',
        'new_project_name' => 'Мой сайт',
        'new_project_domain' => 'example.com',
        'new_project_create' => 'Создать',
        'new_project_cancel' => 'Отмена',
        'tab_keys' => 'Ключи',
        'tab_frontend' => 'Подключение на фронтенде',
        'tab_backend' => 'Подключение на сервере',
        'tab_testing' => 'Тестирование',
        'tab_rules' => 'Правила фильтрации',
        'tab_logs' => 'Логи',
        'key_public' => 'Публичный ключ',
        'key_private' => 'Приватный ключ',
        'key_warning' => 'Никогда не публикуйте приватный ключ! Используйте его только на стороне сервера.',
        'copy' => 'Копировать',
        'copied' => 'Скопировано!',
        'frontend_title' => 'Подключение JavaScript SDK',
        'frontend_auto_title' => 'Вариант 1: Автоматический режим (auto=1, по умолчанию)',
        'frontend_auto_desc' => 'Скрипт автоматически найдёт все формы на странице и защитит их.',
        'frontend_auto_step' => 'Добавьте в <head> или перед </body> вашего сайта:',
        'frontend_manual_title' => 'Вариант 2: Ручной режим (auto=0)',
        'frontend_manual_desc' => 'Скрипт только подключается и собирает данные. Вы сами указываете какие формы защищать.',
        'frontend_manual_step' => 'Подключите скрипт с параметром auto=0:',
        'frontend_manual_examples' => 'Затем защитите нужные формы по селектору:',
        'frontend_by_id' => 'По ID элемента:',
        'frontend_by_class' => 'По CSS-классу:',
        'frontend_by_selector' => 'По произвольному CSS-селектору:',
        'frontend_note' => 'SDK автоматически добавит скрытое поле _antispam_token в каждую защищённую форму перед отправкой.',
        'backend_title' => 'Верификация на сервере',
        'backend_desc' => 'После отправки формы, ваш сервер получит поле _antispam_token. Отправьте его на наш API для проверки:',
        'backend_endpoint' => 'Endpoint верификации',
        'backend_request' => 'Запрос',
        'backend_response' => 'Ответ',
        'backend_examples' => 'Примеры интеграции',
        'backend_score_note' => 'score — оценка от 0.0 (бот) до 1.0 (человек). Рекомендуемый порог: 0.5',
        'testing_title' => 'Тестовая форма',
        'testing_desc' => 'Проверьте работу антиспама для этого проекта. Заполните форму и отправьте — SDK соберёт поведенческие сигналы и сгенерирует токен, затем сервер его проверит.',
        'testing_name' => 'Имя',
        'testing_email' => 'Email',
        'testing_message' => 'Сообщение',
        'testing_submit' => 'Отправить форму',
        'testing_verifying' => 'Проверка...',
        'testing_result_human' => 'Человек обнаружен!',
        'testing_result_bot' => 'Обнаружен бот или верификация не пройдена.',
        'testing_result_error' => 'Ошибка верификации',
        'testing_no_token' => 'Токен _antispam_token не найден. SDK мог не загрузиться.',
        'rules_title' => 'Правила фильтрации',
        'rules_add' => 'Добавить правило',
        'rules_edit' => 'Редактировать правило',
        'rules_name' => 'Название правила',
        'rules_type' => 'Тип',
        'rules_value' => 'Значение',
        'rules_action' => 'Действие',
        'rules_block' => 'Блокировать',
        'rules_allow' => 'Разрешить',
        'rules_priority' => 'Приоритет',
        'rules_active' => 'Активно',
        'rules_inactive' => 'Неактивно',
        'rules_save' => 'Сохранить',
        'rules_cancel' => 'Отмена',
        'rules_delete' => 'Удалить',
        'rules_delete_confirm' => 'Удалить правило',
        'rules_empty' => 'Нет правил фильтрации. Добавьте правила для фильтрации подозрительного трафика.',
        'rules_conditions' => 'Условия',
        'rules_add_condition' => 'Добавить условие',
        'rules_conditions_hint' => 'Все условия должны совпасть (логика И)',
        'rules_condition' => 'Условие',
        'rules_type_ip' => 'IP адрес',
        'rules_type_ip_range' => 'Диапазон IP (CIDR)',
        'rules_type_user_agent' => 'User-Agent',
        'rules_type_header' => 'HTTP заголовок',
        'rules_type_score' => 'Порог скора',
        'logs_title' => 'Логи верификации',
        'logs_all' => 'Все',
        'logs_successful' => 'Успешные',
        'logs_blocked' => 'Заблокированные',
        'logs_filtered' => 'Отфильтрованные',
        'logs_date' => 'Дата/Время',
        'logs_ip' => 'IP адрес',
        'logs_ua' => 'User-Agent',
        'logs_score' => 'Скор',
        'logs_status' => 'Статус',
        'logs_rule' => 'Совпавшее правило',
        'logs_no_data' => 'Нет логов для выбранного фильтра',
        'logs_human' => 'Человек',
        'logs_bot' => 'Бот',
        'logs_filter_blocked' => 'Отфильтровано',
        'logs_prev' => 'Назад',
        'logs_next' => 'Вперёд',
        'logs_page' => 'Страница',
        'logs_filter_ip' => 'Фильтр по IP...',
        'stats_title' => 'Статистика',
        'stats_total' => 'Всего обращений',
        'stats_success' => 'Успешных (человек)',
        'stats_rejected' => 'Отклонено (бот)',
        'stats_chart' => 'График обращений по дням',
        'stats_period' => 'Период',
        'stats_7d' => '7 дней',
        'stats_30d' => '30 дней',
        'stats_90d' => '90 дней',
        'stats_no_data' => 'Нет данных за выбранный период',
        'tab_fields' => 'Поля',
        'fields_title' => 'Пользовательские поля',
        'fields_add' => 'Добавить поле',
        'fields_name' => 'Название поля',
        'fields_empty' => 'Нет пользовательских полей. Добавьте поля для фильтрации логов по параметрам.',
        'fields_delete' => 'Удалить',
        'fields_delete_confirm' => 'Удалить поле',
        'fields_placeholder' => 'например: form, method, source',
        'logs_data' => 'Данные',
        'logs_all_fields' => 'Все',
        'stats_from' => 'С',
        'stats_to' => 'По',
        'stats_show' => 'Показать',
        'stats_custom_range' => 'Свой период',
        'back' => 'Назад',
        'loading' => 'Загрузка...',
    ],
    'en' => [
        'app_title' => 'AntiSpam Shield',
        'app_subtitle' => 'Control Panel',
        'nav_projects' => 'Projects',
        'nav_logout' => 'Logout',
        'login_title' => 'Sign In',
        'login_username' => 'Username',
        'login_password' => 'Password',
        'login_submit' => 'Sign In',
        'login_error' => 'Invalid username or password',
        'projects_title' => 'Projects',
        'projects_add' => 'Add Project',
        'projects_name' => 'Name',
        'projects_domain' => 'Domain',
        'projects_stats' => 'Statistics',
        'projects_details' => 'Details',
        'projects_delete' => 'Delete',
        'projects_delete_confirm' => 'Are you sure you want to delete project',
        'projects_empty' => 'No projects yet. Create your first one!',
        'new_project_title' => 'New Project',
        'new_project_name' => 'My Website',
        'new_project_domain' => 'example.com',
        'new_project_create' => 'Create',
        'new_project_cancel' => 'Cancel',
        'tab_keys' => 'Keys',
        'tab_frontend' => 'Frontend Integration',
        'tab_backend' => 'Server Integration',
        'tab_testing' => 'Testing',
        'tab_rules' => 'Filter Rules',
        'tab_logs' => 'Logs',
        'key_public' => 'Public Key',
        'key_private' => 'Private Key',
        'key_warning' => 'Never expose the private key! Use it only on the server side.',
        'copy' => 'Copy',
        'copied' => 'Copied!',
        'frontend_title' => 'JavaScript SDK Integration',
        'frontend_auto_title' => 'Option 1: Automatic mode (auto=1, default)',
        'frontend_auto_desc' => 'The script will automatically find and protect all forms on the page.',
        'frontend_auto_step' => 'Add to <head> or before </body> of your website:',
        'frontend_manual_title' => 'Option 2: Manual mode (auto=0)',
        'frontend_manual_desc' => 'The script loads and collects data, but does not protect forms automatically.',
        'frontend_manual_step' => 'Include the script with auto=0 parameter:',
        'frontend_manual_examples' => 'Then protect the forms you need by selector:',
        'frontend_by_id' => 'By element ID:',
        'frontend_by_class' => 'By CSS class:',
        'frontend_by_selector' => 'By any CSS selector:',
        'frontend_note' => 'The SDK automatically adds a hidden _antispam_token field to each protected form before submission.',
        'backend_title' => 'Server-Side Verification',
        'backend_desc' => 'After form submission, your server will receive the _antispam_token field. Send it to our API for verification:',
        'backend_endpoint' => 'Verification Endpoint',
        'backend_request' => 'Request',
        'backend_response' => 'Response',
        'backend_examples' => 'Integration Examples',
        'backend_score_note' => 'score — rating from 0.0 (bot) to 1.0 (human). Recommended threshold: 0.5',
        'testing_title' => 'Test Form',
        'testing_desc' => 'Test the antispam integration for this project. Fill out the form and submit — the SDK will collect behavioral signals and generate a token, then the server will verify it.',
        'testing_name' => 'Name',
        'testing_email' => 'Email',
        'testing_message' => 'Message',
        'testing_submit' => 'Submit Form',
        'testing_verifying' => 'Verifying...',
        'testing_result_human' => 'Human detected!',
        'testing_result_bot' => 'Bot detected or verification failed.',
        'testing_result_error' => 'Verification error',
        'testing_no_token' => 'No _antispam_token found. SDK may not have loaded.',
        'rules_title' => 'Filter Rules',
        'rules_add' => 'Add Rule',
        'rules_edit' => 'Edit Rule',
        'rules_name' => 'Rule Name',
        'rules_type' => 'Type',
        'rules_value' => 'Value',
        'rules_action' => 'Action',
        'rules_block' => 'Block',
        'rules_allow' => 'Allow',
        'rules_priority' => 'Priority',
        'rules_active' => 'Active',
        'rules_inactive' => 'Inactive',
        'rules_save' => 'Save',
        'rules_cancel' => 'Cancel',
        'rules_delete' => 'Delete',
        'rules_delete_confirm' => 'Delete rule',
        'rules_empty' => 'No filter rules. Add rules to filter suspicious traffic.',
        'rules_conditions' => 'Conditions',
        'rules_add_condition' => 'Add Condition',
        'rules_conditions_hint' => 'All conditions must match (AND logic)',
        'rules_condition' => 'Condition',
        'rules_type_ip' => 'IP Address',
        'rules_type_ip_range' => 'IP Range (CIDR)',
        'rules_type_user_agent' => 'User-Agent',
        'rules_type_header' => 'HTTP Header',
        'rules_type_score' => 'Score Threshold',
        'logs_title' => 'Verification Logs',
        'logs_all' => 'All',
        'logs_successful' => 'Successful',
        'logs_blocked' => 'Blocked',
        'logs_filtered' => 'Filtered',
        'logs_date' => 'Date/Time',
        'logs_ip' => 'IP Address',
        'logs_ua' => 'User-Agent',
        'logs_score' => 'Score',
        'logs_status' => 'Status',
        'logs_rule' => 'Matched Rule',
        'logs_no_data' => 'No logs for selected filter',
        'logs_human' => 'Human',
        'logs_bot' => 'Bot',
        'logs_filter_blocked' => 'Filtered',
        'logs_prev' => 'Previous',
        'logs_next' => 'Next',
        'logs_page' => 'Page',
        'logs_filter_ip' => 'Filter by IP...',
        'stats_title' => 'Statistics',
        'stats_total' => 'Total Requests',
        'stats_success' => 'Successful (Human)',
        'stats_rejected' => 'Rejected (Bot)',
        'stats_chart' => 'Requests by Day',
        'stats_period' => 'Period',
        'stats_7d' => '7 days',
        'stats_30d' => '30 days',
        'stats_90d' => '90 days',
        'stats_no_data' => 'No data for selected period',
        'tab_fields' => 'Fields',
        'fields_title' => 'Custom Fields',
        'fields_add' => 'Add Field',
        'fields_name' => 'Field Name',
        'fields_empty' => 'No custom fields. Add fields to enable log filtering by custom parameters.',
        'fields_delete' => 'Delete',
        'fields_delete_confirm' => 'Delete field',
        'fields_placeholder' => 'e.g. form, method, source',
        'logs_data' => 'Data',
        'logs_all_fields' => 'All',
        'stats_from' => 'From',
        'stats_to' => 'To',
        'stats_show' => 'Show',
        'stats_custom_range' => 'Custom range',
        'back' => 'Back',
        'loading' => 'Loading...',
    ],
];

function t(string $key): string {
    global $LANG;
    $lang = $_SESSION['lang'] ?? 'ru';
    return $LANG[$lang][$key] ?? $key;
}

function currentLang(): string {
    return $_SESSION['lang'] ?? 'ru';
}
